remote: true

experienceLevel:
  internship: false
  entry: false
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - service desk
  - l1, l2 support
  

locations:
  - India

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 200


llm_model_type: gemini
# llm_model: 'gemini-1.5-flash-latest'
llm_model: 'gemini-1.5-pro'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'